# Generated by Django 4.1.7 on 2023-04-03 17:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='Usuario', max_length=32)),
                ('Apellido', models.CharField(default='Apellido', max_length=32)),
                ('Email', models.EmailField(max_length=254)),
                ('Rol_del_usuario', models.CharField(default='Vendedor', max_length=32)),
                ('Nro_de_celular', models.CharField(default='999999999', max_length=32)),
                ('Fecha_de_ingreso', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
